[Interface]
PrivateKey = EFIypM4lWf1q+krnYR8daEs9xKrJiwtbstwvpf6N21A=
Address = 10.66.66.2/32
DNS = 1.1.1.1
MTU = 1380

[Peer]
PublicKey = MKSSy8US62rzkNidWv43kR1Rel5j44XHLLHCB2LjQiw=
Endpoint = 216.9.227.124:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

CLIENT_PUBLIC_KEY = QXFnH3B6GJMKe0u0kEYldkXiDIgSSvkfeaQFquk3Gyc=
SERVER_PUBLIC_KEY = MKSSy8US62rzkNidWv43kR1Rel5j44XHLLHCB2LjQiw=




