[Interface]
PrivateKey = QMqx1Wk+hNGUzggIH/q5Sr7dNR70De9CSqNILhiYm0c=
Address = 10.99.99.2/24
MTU = 1280
Table = off

[Peer]
# USA VPS
PublicKey = /AwOTQrxX09yJ2f+027DNKDXQWub7rydvprXgsqio0Y=
Endpoint = 216.9.227.124:51821
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

