[Interface]
PrivateKey = EM8jJGzUk+xFkI7VOjENCL8zqYkYhlh0OAdbRoUIXXQ=
Address = 10.99.99.1/24
ListenPort = 51821
MTU = 1280
Table = off
PostUp = iptables -I FORWARD 1 -i %i -j ACCEPT; iptables -I FORWARD 1 -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Moscow VPS
PublicKey = oz2pFtwM3sBP/nzDV4SPIgNyw4r7SsqZTN86cWSEOmU=
AllowedIPs = 10.99.99.2/32
PersistentKeepalive = 25
